version: '3.7'
services:
    minio1:
      image: minio/minio:RELEASE.2019-01-10T00-21-20Z
      hostname: minio1
      volumes:
        - minio1-data:/export
      networks:
        - adfree-net
      deploy:
        restart_policy:
          delay: 10s
          max_attempts: 10
          window: 60s
        placement:
          constraints:
            - node.labels.minio==true
        labels:
          - "traefik.port=9000"
          - "traefik.docker.network=adfree-net"
          - "traefik.frontend.rule=Host:minio.example.com"
          - "traefik.backend.loadbalancer.sticky=true"
      command: server http://minio1/export
      secrets:
        - secret_key
        - access_key

